CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR(255) not null ,
    login_id VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(50) not null ,
    generation INTEGER not null ,
    CONSTRAINT uk_members_login_id UNIQUE (login_id)
);
