CREATE TABLE refresh_tokens(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    token VARCHAR(512) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_refresh_tokens_member_id UNIQUE (member_id)
);